#:kivy 2.3.0
<BaseMDNavigationItem>:
    MDNavigationItemIcon:
        icon: root.icon

    MDNavigationItemLabel:
        text: root.text

<NavBar>:
    MDNavigationBar:
        BaseMDNavigationItem:
            icon: "home"
            text: "Home"
            active: True
            navigate_to: "home_screen"

        BaseMDNavigationItem:
            icon: "intro"
            text: "Intro"
            navigate_to: "home_screen"
